### ISSUE TITLE
メソッドsortAscOrderByの引数sortTypeの型について

### ISSUE THREAD

**Issue by matsumoto777** [KienSengSaw91/training1-uitableview-iphone#1]
sortAscOrderByでソート順をStringで受けているために下記2点の問題がある。

1) 引数sortTypeに渡すべき内容について、メソッドを解析しないとわからないのは不親切。
2) タイプミスによりつまらないバグが発生する可能性がある。

なので、引数sortTypeはStringでなくenumにすべき。

**Comment by matsumoto777** [comment]
sortTypeの型をSortTypeにできませんか？

func sortAscOrderBy(sortType : String?){
　↓
func sortAscOrderBy(sortType : SortType){

**Comment by matsumoto777** [comment]
SortTypeをそのまま表示用文字列として扱っていますが、本来、それはするべきではないです。

SortTypeは、将来、ユーザー設定として端末ストレージに永続化されることが予想されます。
（「アプリ再開後もソート順を維持すること」という要件があれば永続化する必要が出ます）

表示用文字列は、様々な理由で変えることがあります。

このとき、表示用文字列がKeyとなっていたら変更できません。

というわけで、SortTypeと表示用文字列は別に定義すべきです。
また、SortTypeはIntとすべきです。

**Comment by matsumoto777** [comment]
sortTypeListとclass SortTypeDataは重すぎます。
このトレーニングの趣旨から外れています。
下記のように書いてください。これで要件は十分満たせます。

```
self.sortTypeLabel.text = "Ascending ID"
```

ちなみに、本格的に書くのであれば、AppDevTeam-work/LionFX2iPad の class RSide が参考になります。

**Comment by MaroSasaki** [comment]
sortTypeList and class SortTypeData are too heavy.
You might be diverting a little bit away from the purpose of the training.
Please write as below, this is sufficient.

self.sortTypeLabel.text = "Ascending ID"

If you want to write it in genuine way ,class RSide of AppDevTeam-work/LionFX2iPad might be a good reference.

**Comment by matsumoto777** [comment]
RValue.swiftは不要になりましたので消してください。

**Comment by KienSengSaw91** [comment]
@matsumoto777 
- I change to "Ascending ID" and "Ascending Name" variable.

**Comment by KienSengSaw91** [comment]
> RValue.swiftは不要になりましたので消してください。

@matsumoto777 
RValue.swift class is removed.

**Comment by matsumoto777** [comment]
もしクラスや変数が不要になったら、あなたはそれを削除するべき
If class or variable is no longer needed, you should delete it

**Comment by KienSengSaw91** [comment]
> もしクラスや変数が不要になったら、あなたはそれを削除するべき
> If class or variable is no longer needed, you should delete it

@matsumoto777 
understand and thank you.
