### ISSUE TITLE
無駄なコード indications of useless code.

### ISSUE THREAD

**Issue by matsumoto777** [KienSengSaw91/training1-uitableview-iphone#2]
下記、無駄なコードに対する指摘です。
The following is indications of useless code.

1) sortAscOrderByの case default は、unreachable blockなので不要だと思う。
2) また、変数tempSortIdListは無駄な変数宣言です。コードの読みやすさにも貢献しません。

1) In sortAscOrderBy, "case default" is an unreachable block, so it's unnecessary.
2) And "tempSortIdList" is a useless variable declaration. It does not contribute to code readability.

**Comment by matsumoto777** [comment]
"tempSortIdList"は無駄な変数宣言だと思うが、残している理由を教えてほしいです。

**Comment by KienSengSaw91** [comment]
@matsumoto777 
- I have remove the  sortAscOrderBy default case.
- I have remove tempSortIdList variable.

**Comment by KienSengSaw91** [comment]
> "tempSortIdList"は無駄な変数宣言だと思うが、残している理由を教えてほしいです。

@matsumoto777 
The "tempSortIdList" is use to store new sorted ascending ID list in func sortAscOrderBy()
let tempSortIdList = members.sorted(by: {$0.id < $1.id})

**Comment by matsumoto777** [comment]
I think that there is no problem with the code below.
```
members = members.sorted(by: {$0.id < $1.id})
```

**Comment by matsumoto777** [comment]
or simply
```
members.sort(by: {$0.id < $1.id})
```

**Comment by KienSengSaw91** [comment]
> or simply
> 
> ```
> members.sort(by: {$0.id < $1.id})
> ```

@matsumoto777 
Thank you.
I had do an update for this issue
- remove "tempSortIdList" & "tempSortNameList"
- simplify code to members.sort()

**Comment by matsumoto777** [comment]
OK!
Your training-1 is finished.
Thank you.
